### PR TITLE
Use dynamic canvas ID for ignoring zoom

### LINKED ISSUE #28: Zoom not working in production
as reported by @davekinkead

### PR DESCRIPTION
**Pull request by geoffreyd**
Fixes #28

### CODE REVIEW

**Comment by davekinkead** [comment]
Doh! thanks

**Comment by davekinkead** [comment]
Had to change this `event.target.id != mapper.DOM.id` to `event.target.id != mapper.DOM.id` as the DOM id user specified and can't be hard coded

**Comment by geoffreyd** [comment]
is this working after your change? I've tried on reasons.io and it's not working.

The reason that I had `if (event.target.id != 'reasons-'+mapper.DOM.id) {` is because this is how the canvas ID is created: 

https://github.com/davekinkead/reasons/blob/0456164c3dd39a78a208d1795853c346fbf986ac/lib/view.js#L46-L50

Were `mapper.DOM.id` is the user specified name. For the scroll, I need to check if the scroll event's target is the canvas, not the wrapper.

**Comment by davekinkead** [comment]
Geoff - this is working strangely.  It seems that the scroll event wouldn't trigger when the reference was to the canvas `reasons-` but does when the reference is the parent div?

**Pull request closed without merging**
